<a href="https://colab.research.google.com/github/romanowiczadam/data-sb/blob/master/kurs_datascience/01_wprowadzenie/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
np.__version__

'1.18.4'

# 2.1.Norma_wektora_dlugosc_wektora

In [0]:
# norma wektora w przestrzeni R2
# |v| = sqrt(   (v_1)**2    +    (v_2)**2  )

# norma wektora w przestrzeni R2
# |v| = sqrt(   (v_1)**2    +    (v_2)**2  +....+ (v_n)**2)

In [0]:
# obliczenie normy wektora w przestrzeni R2
v1 = np.array([-1, 4])
# aby obliczyc norme wektora v1należy użyć funkcji odnoszącej się do algebry liniowej linalg
v1_n = np.linalg.norm(v1) 
print(v1_n)

4.123105625617661


In [0]:
# obliczenie normy wektora w przestrzeni R3
v2 = np.array([-1, 4, 4])
v2_n = np.linalg.norm(v2)
print(v2_n)
# obliczenie normy wektora w przestrzeni R5
v3 = np.array([-1, 4, 4, -7, 3])
v3_n = np.linalg.norm(v3)
print(v3_n)

5.744562646538029
9.539392014169456


In [0]:
# obliczenie odległości pomiędzy dwoma punktami w przestrzeni Rn
# d(a, b) = sqrt(   (a1 - b1)**2    +    (a2 - b2)**2  +....+ (an - bn)**2)
p = np.array([3, 0])
q = np.array([0, 4])
# aby policzyć odległosc wykorzystujemy ta sama funkcję norm
v_pq = np.linalg.norm(p - q) 
print(v_pq)

p_2 = np.array([3, 0, 6, -4])
q_2 = np.array([0, 4, 4, 3])
# aby policzyć odległosc wykorzystujemy ta sama funkcję norm
v_pq_2 = np.linalg.norm(p_2 - q_2) 
print(v_pq_2)

5.0
8.831760866327848


# 2.2.Mnozenie_macierzy

In [0]:
# Mamy dwie macierze:
# A (m -wierszy i n - kolumn) oraz
# B (n -wierszy i p - kolumn)
# Aby mnożenie A x B było możliwe n kolumn w lewej macierzy musi być równe
# liczbie wierszy w drugiej macierzy
# Mnożenie macierzy nie jest przeminne A x B != B x A

# przyklad mnożenia miacierzy
A = np.array([[2, 4], [8, -2]])
B = np.array([[1], [7]])

print(A, '\n')
print(B, '\n')
# mnozenie

Z = np.dot(A, B)
print('Wynik:','\n', Z)
print('----------')
C = np.array([[2, 4, 1], [8, -2, 1]])
D = np.array([[1, -2, -2], [7,  4, -9], [1, 3,  4]])

print(C, '\n')
print(D, '\n')
# mnozenie

Z_2 = np.dot(C, D)
print('Wynik:','\n', Z_2)



[[ 2  4]
 [ 8 -2]] 

[[1]
 [7]] 

Wynik: 
 [[30]
 [-6]]
----------
[[ 2  4  1]
 [ 8 -2  1]] 

[[ 1 -2 -2]
 [ 7  4 -9]
 [ 1  3  4]] 

Wynik: 
 [[ 31  15 -36]
 [ -5 -21   6]]


# 2.3.Algebra_liniowa_wyznacznik

In [0]:
# wyznacznik macierzy
# obliczenie wyznacznika  macierz jednoelementowa. element = wyznacznik
# macierz 2x2
# a11   a12
# a21   a22   W   =   a11 * a 22   +   a12 * a21 = W     
#
# macierz 3 x 3
# a11  a12  a13
# a21  a22  a23
# a31  a32  a33   W  = a11 * a22 * a33  +   a21  * a32  * a13 + a31 * a12 * a23 -
#                     a21 * a12 * a33  -   a11 * a32 * a23  - a31 * a22 * a13 

In [6]:
# liczenie wyznacznika dla macierzy 2x2
E = np.array([[3, 2], [9, -7]])
w_1 = np.linalg.det(E)
print(E, '\n', w_1)

[[ 3  2]
 [ 9 -7]] 
 -38.99999999999999


In [18]:
# slad macierzy to suma wartości na przekątnej
# macierz 3 x 3
# a11  a12  a13
# a21  a22  a23
# a31  a32  a33  tr   = a11 + a22 + a33
t_1 = np.trace(E)
print(t_1)

-4


In [12]:
# macierz jednostkowa jest to macierz kwadratowa, ktorej wspolczynniki na przekatnej sa rowne 1
# generowanie macierzy jednostkowej
F = np.eye(4, dtype='int')
print(F)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [19]:
# macierz odwrotna - macierz kwadratowa stopnia n. Macierz A posiada macierz
# odwrotna, gdy istnieje taka macierz B, że     A x B = B x A = I
# czyli po pomnożeniu tych  macierzy powstanie macierz jednostkowa
# macierz odwrotna do macierzy E
O_E = np.linalg.inv(E)
print(O_E)
# sprawdzenie
SPR_E = np.dot(O_E, E)
SPR_E_2 = np.dot(E, O_E)
print(SPR_E, '\n', SPR_E_2)

[[ 0.17948718  0.05128205]
 [ 0.23076923 -0.07692308]]
[[ 1.00000000e+00  1.11022302e-16]
 [-5.55111512e-17  1.00000000e+00]] 
 [[ 1.00000000e+00 -5.55111512e-17]
 [-5.55111512e-17  1.00000000e+00]]


In [21]:
# transponowanie macierzy - zamina wierszy na kolumny, kolumn na wiersze
print(E)
E_T = np.transpose(E) # można też
E_T_2 = E.T
print(E_T, '\n', E_T_2)

[[ 3  2]
 [ 9 -7]]
[[ 3  9]
 [ 2 -7]] 
 [[ 3  9]
 [ 2 -7]]


In [0]:
2

# 2.4.Algebra_liniowa_rozwiazywanie_ukladow_rownan

In [0]:
# układ rownan
# a11* x1 + a12 * x 2 +....+ a1n * xn  = b1
# a21* x1 + a22 * x 2 +....+ a2n * xn  = b2
# ...* .. + ...* .. +....+ ..... * ... = ..
# am1* x1 + am2 * x 2 +....+ amn * xn  = bm

# macierze z układu równań
# |a11   a12  ....  a1n|  |x1|  |b1|
# |a21   a22  ....  a2n|  |x2|  |b2|
# |...   ...  ....  ...|  |..|  |..|
# |am1   am2  ....  amn|  |xn|  |bn|

# 1. macierz współczynników
# 2. wektor niewiadomych
# 3. wektor wyrazow wolnych
# 
# A x X =B
# gdy macierz jest kwadratowa mozemy obliczyc X za pomoca:
# X = A_inv  x   B
# przyklad rozwiazania uklkadu rownan(tylko w przypadku macierzy kwadratowych)
#  2x +4y = 10
#  x - y  = -1



In [5]:
# macierz współczynnikow
A_m = np.array([[2, 4], [1, -1]])
B_m = np.array([[10],[-1]])
print(A_m)
print(B_m)

[[ 2  4]
 [ 1 -1]]
[[10]
 [-1]]


In [9]:
# macierz odwrotna do macierzy A
A_minv = np.linalg.inv(A_m)
print(A_minv)
X = np.dot(A_minv, B_m)
print(X)

[[ 0.16666667  0.66666667]
 [ 0.16666667 -0.33333333]]
[[1.]
 [2.]]
