<a href="https://colab.research.google.com/github/romanowiczadam/data-sb/blob/master/kurs_datascience/01_wprowadzenie/3_1_Funkcje_statystyczne.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 3.1.Fukcje_statystyczne

In [0]:
import numpy as np

In [16]:

price = np.array([[12.4, 12.8, 11.9, 1000],
                  [12.5, 13,   11.7, 2000],
                  [12.2, 13.4, 13.2, 1500]])
print(price)
# dodawanie wszystkich elementów tablicy
print(price.sum())
# sumowanie po kolumnach
print(price.sum(axis = 0))
# sumowanie po kolumnach
print(price.sum(axis = 1))
# może też być
print(np.sum(price))
print('----------------')
# minimalna wartosc w tablicy
print(np.min(price))
# minimalne wartosci z poszczegolnych kolumn
print(np.min(price, axis = 0))
# minimalne wartosci z poszczegolnych wierszy
print(np.min(price, axis = 1))
# maxymalne wartosci z poszczegolnych kolumn
print(np.max(price, axis = 0))
# maxymalne wartosci z poszczegolnych wierszy
print(np.max(price, axis = 1))
print('----------------')
# mediana z wszystkich wartosci w tablicy
print(np.median(price))
# średnia z wszystkich wartosci w tablicy
print(np.mean(price))
# średnia dla poszczegolnych kolumn
print(np.mean(price, axis = 0))
# średnia dla poszczegolnych wierszy
print(np.mean(price, axis = 1))
print('----------------')
# odchylenie standardowe
print(np.std(price))
# wariancja dla poszczegolnych kolumn
print(np.var(price, axis = 0))

[[  12.4   12.8   11.9 1000. ]
 [  12.5   13.    11.7 2000. ]
 [  12.2   13.4   13.2 1500. ]]
4613.1
[  37.1   39.2   36.8 4500. ]
[1037.1 2037.2 1538.8]
4613.1
----------------
11.7
[  12.2   12.8   11.7 1000. ]
[11.9 11.7 12.2]
[  12.5   13.4   13.2 2000. ]
[1000. 2000. 1500.]
----------------
12.9
384.425
[  12.36666667   13.06666667   12.26666667 1500.        ]
[259.275 509.3   384.7  ]
----------------
675.6498737326901
[1.55555556e-02 6.22222222e-02 4.42222222e-01 1.66666667e+05]


In [21]:
A = np.array([[1,2,3],[1,2,3]])
B = np.array([[1],[2],[3]])
print(A)
print(B)
C = np.dot(A, B)
print(C)

[[1 2 3]
 [1 2 3]]
[[1]
 [2]
 [3]]
[[14]
 [14]]
