<a href="https://colab.research.google.com/github/romanowiczadam/data-sb/blob/master/1_Podstawy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1.1.Tablice

In [0]:
from google.colab import drive
drive.mount('/content/drive')

In [2]:
import numpy as np 
np.__version__

'1.18.4'

In [0]:
help(np.array)

In [0]:
print(dir(np))

In [0]:
x = np.array([1.1, 2, 3, 4, 5])

print(x)
type(x)
print(x.ndim) #sprawdza wymiar tablicy
print(x.shape) #sprawdza ksztalt tablicy
print(x.size) #sprawdza rozmiar tablicy
print(x.dtype) # określanie typu danych w tablicy

[1.1 2.  3.  4.  5. ]
1
(5,)
5
float64


In [0]:
# tablica dwuwymiarowa
y = np.array([[1, 2], [7, 9]])
print(y)
print(y.ndim) #sprawdza wymiar tablicy
print(y.shape) #sprawdza ksztalt tablicy
print(y.size) #sprawdza rozmiar tablicy
print(y.dtype) # określanie typu danych w tablicy

[[1 2]
 [7 9]]
2
(2, 2)
4
int64


In [0]:
# tablica dwuwymiarowa # 2
y_2 = np.array([[1, 2], [7, 9], [1, 1]])
print(y_2)
print(y_2.ndim) #sprawdza wymiar tablicy
print(y_2.shape) #sprawdza ksztalt tablicy (najpierw podaje ilosc wierszy, a pozniej kolumn)
print(y_2.size) #sprawdza rozmiar tablicy
print(y_2.dtype) # określanie typu danych w tablicy

[[1 2]
 [7 9]
 [1 1]]
2
(3, 2)
6
int64


In [0]:
# tablica trójwymiarowa
z = np.array([  [[1, 2, 4, 3], 
                 [7, 9, 7, 1]],
              
                [[2, 1, 9, 9],
                 [8, 4, 5, 2]],
              
                [[2, 1, 9, 9],
                 [8, 4, 5, 2]]  ])
print(z)
print(z.ndim) #sprawdza wymiar tablicy
print(z.shape) #sprawdza ksztalt tablicy
print(z.size) #sprawdza rozmiar tablicy (ilosc elementow liczona jest''od zewnatrz')
print(z.dtype) # określanie typu danych w tablicy

[[[1 2 4 3]
  [7 9 7 1]]

 [[2 1 9 9]
  [8 4 5 2]]

 [[2 1 9 9]
  [8 4 5 2]]]
3
(3, 2, 4)
24
int64


# 1.2.Typy_Danych

In [30]:
A = np.array([1, 2, 3], dtype = 'float')  # możemy ręcznie przekazać typ danych za pomoca dtyp(np 'float lub complex)
print(A, A.dtype)
# na całkowite trzeba uważac, bo zaokragla w dol
B = np.array([1.2, 2.8, 3.5], dtype = 'int')  # możemy ręcznie przekazać typ danych za pomoca dtyp(np 'float lub complex)
print(B, B.dtype)

[1. 2. 3.] float64
[1 2 3] int64


In [32]:
# przykładowy piksel można wpiasać, aby typ danych to była 8 bitowa liczba całkowita
# żeby dana zawierała mniej miejsca
C = np.array([12, 47, 22], dtype = np.int8) # można tez uzyc zmiennej typu uint8
print(C.dtype)


int8


# 1.3.Tworzenie_Tablic

In [33]:
# funkncje pomocne w procesie tworzenia tablic

# tablica składająca się z samych zer
np.zeros(shape =(3, 4, 2) )

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [34]:
# tablica składajaca się z samych jedynek
np.ones(shape = (5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
# tworzenie tablicy z dowolnymi warotosciami
np.full(shape = (3, 3), fill_value = 4, dtype = 'int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [41]:
# analogicznie do range tylko w bibliotece numpy
print(np.arange(10))
# można ustawieć by odliczanie zaczynalo sie od innej liczby za pomoca start (stop)
# można też wybrac dany krok za pomoca step
print(np.arange(start=10, stop = 100, step = 10))
# w drugą stronę
print(np.arange(start = 100, stop = 50, step = -10))
# mozna tez stosowac do float

[0 1 2 3 4 5 6 7 8 9]
[10 20 30 40 50 60 70 80 90]
[100  90  80  70  60]


In [42]:
# funkcja linspace pozwala wpisac do tablicy daną ilość równo rozłożonych liczb z danego przedziału
print(np.linspace(start= 3, stop= 8, num= 10))

[3.         3.55555556 4.11111111 4.66666667 5.22222222 5.77777778
 6.33333333 6.88888889 7.44444444 8.        ]


In [50]:
# zmiana kształtu danych
A = np.arange(15)
print(A)
A_2 = A.reshape((3,5))
print(A_2)
# jeśli chcemy, żeby python sam dobral odpowiednią liczbę kolumn/wierszy; wpisujemy -1
A_3 = A.reshape((3,-1))
print(A_3)
B = np.arange(16)
B_2 = B.reshape((2, 2, -1))
print('---------------')
print(B_2)



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
---------------
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


# 1.4.Podstawowe_operacje_na_tablicach

In [9]:
AN = np.array([8, 6, 5, 1])
AD = np.array([7, 2, 2 ,3])
print(AN, AD)
print(AN + AD)  # można też: np.add(AN, AD)
print(AN - AD) # można też: np.subtract(AN, AD)
print(AN * AD)  # można też: np.multiply(AN, AD)
print(AN / AD)  # można też: np.divide(AN, AD)
print(AD + 3)
print(AD * 2)
print('-------------')


[8 6 5 1] [7 2 2 3]
[15  8  7  4]
[ 1  4  3 -2]
[56 12 10  3]
[1.14285714 3.         2.5        0.33333333]
[10  5  5  6]
[14  4  4  6]


In [19]:

X = np.array([[2, 5], [9, 0]])
Y = np.array([[1, 3], [5, 3]])
print(X, '\n')
print(Y)
print('-----------')
# zwykłe mnożenie
print(X * Y)
# mnożenie macierzowe
print(np.dot(X, Y)) # można też wpisać 
print(X.dot(Y)) # lub
print(X @ Y)

[[2 5]
 [9 0]] 

[[1 3]
 [5 3]]
-----------
[[ 2 15]
 [45  0]]
[[27 21]
 [ 9 27]]
[[27 21]
 [ 9 27]]
[[27 21]
 [ 9 27]]


# 1.5.Generowanie liczb pseudolosowych

In [15]:
# ziarno liczb losowych (zawsze wychodzi ta sama losowa liczba)
np.random.seed(0)
# losowanie liczb z rozkładu normalnego
print(np.random.randn(10)) # losuje daną ilość liczb pseudolosowych o średniej 0 i odchyleniu standardowym 1
print(np.random.randn(10, 5)) # drugi parametr sprawia, że tworzona jest tablica
print(np.random.rand()) # rand losuje liczbę losową z przedziału 0 - 1 (jedyna jest wylaczona)
# drugi parametr też daje tablice
print(np.random.randint(10)) #randint zwóci liczbę całkowita do 10 (10 wylaczone)
print(np.random.randint(low = -10, high = 5, size = 3)) #mozna podac tez parametr startowy i koncowy, size ilosc liczb
print(np.random.choice([5, 10, 15, 20])) # wybiera jedną liczbę z przedziału, # trzeba podac liste
print(np.random.choice(['Ania', 'Adas'])) # mozna podac nazwy

[ 1.76405235  0.40015721  0.97873798  2.2408932   1.86755799 -0.97727788
  0.95008842 -0.15135721 -0.10321885  0.4105985 ]
[[ 0.14404357  1.45427351  0.76103773  0.12167502  0.44386323]
 [ 0.33367433  1.49407907 -0.20515826  0.3130677  -0.85409574]
 [-2.55298982  0.6536186   0.8644362  -0.74216502  2.26975462]
 [-1.45436567  0.04575852 -0.18718385  1.53277921  1.46935877]
 [ 0.15494743  0.37816252 -0.88778575 -1.98079647 -0.34791215]
 [ 0.15634897  1.23029068  1.20237985 -0.38732682 -0.30230275]
 [-1.04855297 -1.42001794 -1.70627019  1.9507754  -0.50965218]
 [-0.4380743  -1.25279536  0.77749036 -1.61389785 -0.21274028]
 [-0.89546656  0.3869025  -0.51080514 -1.18063218 -0.02818223]
 [ 0.42833187  0.06651722  0.3024719  -0.63432209 -0.36274117]]
0.29614019752214493
2
[-1 -8  4]
20
Ania


In [14]:
# gdy chcemu przetasowac istniejace dane
data = np.arange(5)
print(data)
np.random.shuffle(data) # UWAGA - wbrew intuicji funkcja ta zmienia dane bez przypisywania !!
print(data)

[0 1 2 3 4]
[1 0 2 4 3]


# 1.6.Funkcje_w_bibliotece_NumPy

In [18]:
print(np.exp(1)) # e do x (exponent) (e - stala Eulera)
print(np.sqrt(9)) # pierwiastek
print(np.all([1, 4, 0])) # funcja przechodzi po obiekcie iterowalnym i bada czy posczegolne elementy zwracaja wartosc logiczna false czy true
# jesli choc jedna Fasle zworci false, jesli wszystkie True zwroci True
print(np.any([0, 0, 1])) # działa na odwrót do all

2.718281828459045
3.0
False
True


In [19]:
A = np.random.rand(5)
print(A)

[0.0641475  0.69247212 0.56660145 0.26538949 0.52324805]


In [29]:
ar = np.argmax(A) # największy element 
print(ar) # element pierwszy 0.69...
print(A[np.argmax(A)]) # sprytny wybór tego argumentu
print(A[np.argmin(A)]) # najniższa wartosc
# sortowanie roznąco
print(np.argsort(A))
print(np.max(A)) # zwracanie wartosci największej
print(np.min(A)) # zwracanie wartosci najmniejszes
print(np.mean(A)) # zwracanie wartosci sredniej
print(np.median(A)) # zwracanie mediany
print(np.std(A)) # zwracanie odchylenia standardowego

1
0.6924721193700198
0.06414749634878436
[0 3 4 2 1]
0.6924721193700198
0.06414749634878436
0.4223717228663049
0.5232480534666997
0.22667178530825793


# 1.7.Indeksowanie_Wycinanie

In [62]:
C = np.arange(20)
print(C)
np.random.shuffle(C)
print(C)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0 17  1 16  6 12 14 10  4 13 18  7  9  3 19  2  8 15  5 11]


In [63]:
# wycinanie
print(C[2]) # tylko element trzeci
print(C[2:]) # od trzeciego elementu do konca
print(C[:2]) # tylko do trzeciego elementu
print(C[2:6]) # od trzeciego elementu do siódmego
print(C[[2, 5, 6, 7]]) # konkretne elementy musi byc lista indeksow
print(C[-1])  # ostatnia wartosc

1
[ 1 16  6 12 14 10  4 13 18  7  9  3 19  2  8 15  5 11]
[ 0 17]
[ 1 16  6 12]
[ 1 12 14 10]
11


In [64]:
C = C.reshape(4, 5)
print(C)

[[ 0 17  1 16  6]
 [12 14 10  4 13]
 [18  7  9  3 19]
 [ 2  8 15  5 11]]


In [65]:
# wycinanie z tablicy
print(C[0]) # wycięcie wiersza
print(C[:,1]) # wycięcie kolumny
# wycinanie konkretnego elementu
print(C[0,4])
# wycinanie fragmentu tablicy
print(C[1:3,1:4]) # print(C[indesky wierszów, indeksy kolumn]) 

[ 0 17  1 16  6]
[17 14  7  8]
6
[[14 10  4]
 [ 7  9  3]]


In [66]:
# przypisanie nowego elementu w danym miejscu tablicy
print(C)
C[1, 1] = 111
print(C)

[[ 0 17  1 16  6]
 [12 14 10  4 13]
 [18  7  9  3 19]
 [ 2  8 15  5 11]]
[[  0  17   1  16   6]
 [ 12 111  10   4  13]
 [ 18   7   9   3  19]
 [  2   8  15   5  11]]


# 1.8.Iteracja_po_tablicah

In [87]:
D = np.arange(20)
np.random.shuffle(D)
D = D.reshape(5,4)
print(D)
print(D.dtype)

[[ 1 13 15  9]
 [ 2  6 17 18]
 [11 12  0  5]
 [ 8  7 16 19]
 [ 3  4 14 10]]
int64


In [89]:
# iteracja po wierszach
for row in D:
  print(row)
# tylko 3 kolumny
for row in D:
  print(row[:3])
# iteracja po elementach (zamiast item może być wpisane cokolwiek)
# trzeba wypłaszczyć tablice używająć funkcji flat
for item in D.flat:
  print(item)


[ 1 13 15  9]
[ 2  6 17 18]
[11 12  0  5]
[ 8  7 16 19]
[ 3  4 14 10]
[ 1 13 15]
[ 2  6 17]
[11 12  0]
[ 8  7 16]
[ 3  4 14]
1
13
15
9
2
6
17
18
11
12
0
5
8
7
16
19
3
4
14
10


In [93]:
# zmiana rozmiaru tablicy
print(D.shape)
print(D)

(5, 4)
[[ 1 13 15  9]
 [ 2  6 17 18]
 [11 12  0  5]
 [ 8  7 16 19]
 [ 3  4 14 10]]


In [103]:
D.reshape(10, 2)
print(D)
# metodą ravel można łątwo wrócić do ,,płaskiej" postaci naszej tablicy
D.ravel()

[[ 1 13 15  9]
 [ 2  6 17 18]
 [11 12  0  5]
 [ 8  7 16 19]
 [ 3  4 14 10]]


array([ 1, 13, 15,  9,  2,  6, 17, 18, 11, 12,  0,  5,  8,  7, 16, 19,  3,
        4, 14, 10])

In [104]:
# transponowanie tablicy -> zmiana wierszów na kolmny i kolumn na wiersze
print(D.T)

[[ 1  2 11  8  3]
 [13  6 12  7  4]
 [15 17  0 16 14]
 [ 9 18  5 19 10]]


In [112]:
# maski logiczne
F = np.arange(start = -10, stop = 10, step = 0.5)
print(F)
F = F.reshape(10, -1)
print(F)
# maska logiczna - gdzie są wartosci ujemne a gdzie dodatnie
print(F > 0)
# wycięcie wartosci dodatnich
print(F[F >0])
print(F)

[-10.   -9.5  -9.   -8.5  -8.   -7.5  -7.   -6.5  -6.   -5.5  -5.   -4.5
  -4.   -3.5  -3.   -2.5  -2.   -1.5  -1.   -0.5   0.    0.5   1.    1.5
   2.    2.5   3.    3.5   4.    4.5   5.    5.5   6.    6.5   7.    7.5
   8.    8.5   9.    9.5]
[[-10.   -9.5  -9.   -8.5]
 [ -8.   -7.5  -7.   -6.5]
 [ -6.   -5.5  -5.   -4.5]
 [ -4.   -3.5  -3.   -2.5]
 [ -2.   -1.5  -1.   -0.5]
 [  0.    0.5   1.    1.5]
 [  2.    2.5   3.    3.5]
 [  4.    4.5   5.    5.5]
 [  6.    6.5   7.    7.5]
 [  8.    8.5   9.    9.5]]
[[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.
 9.5]
[[-10.   -9.5  -9.   -8.5]
 [ -8.   -7.5  -7.   -6.5]
 [ -6.   -5.5  -5.   -4.5]
 [ -4.   -3.5  -3.   -2.5]
 [ -2.   -1.5  -1.   -0.5]


In [115]:
# łączenie dwóch warunków
# aby podać warunki and należy użyć funcji bitwise
# funkcja ta zwraca nam maskę
print(np.bitwise_and(F > -1, F < 1))
print(F[np.bitwise_and(F > -1, F < 1)])
print(np.bitwise_or(F > 5, F < -5))
print(F[np.bitwise_or(F > 5, F < -5)])

[[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False  True]
 [ True  True False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]
[-0.5  0.   0.5]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[-10.   -9.5  -9.   -8.5  -8.   -7.5  -7.   -6.5  -6.   -5.5   5.5   6.
   6.5   7.    7.5   8.    8.5   9.    9.5]
