<a href="https://colab.research.google.com/github/romanowiczadam/data-sb/blob/master/kurs_datascience/05_DL_Podstawy/02_Keras_wstep.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd 

import plotly.express as px
import tensorflow as tf
tf.__version__

'2.2.0'

# Wprowadzenie - pierwszy model

In [2]:
# utworzenie instancji klasy Sequential
from tensorflow.keras.models import Sequential

model = Sequential()
print(model)

In [0]:
#dodawanie standrdowej warstwy - gęsto połączoną Dense
# units - liczba neuronow
# inout_shape - ilość zmiennych opisujących naszą zmienną docelową
from tensorflow.keras.layers import Dense

model.add(Dense(units = 4, input_shape = (10,)))

In [0]:
# wyświetlanie podsumowania modelu
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 4)                 44        
Total params: 44
Trainable params: 44
Non-trainable params: 0
_________________________________________________________________


In [0]:
# dodanie kolejnej warstwy (2 neuronów)
model.add(Dense(units = 2))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 4)                 44        
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 10        
Total params: 54
Trainable params: 54
Non-trainable params: 0
_________________________________________________________________


In [0]:
# funkcje aktywacji

In [4]:
# liniowa funkcja aktywacji
from tensorflow.keras.activations import linear

random_data = np.linspace(start = -3, stop = 3, num = 300)
data = pd.DataFrame({'data' : random_data, 'linear' : linear(random_data)})
data.head()

data    linear
0 -3.000000 -3.000000
1 -2.979933 -2.979933
2 -2.959866 -2.959866
3 -2.939799 -2.939799
4 -2.919732 -2.919732

In [0]:
px.line(data, x = 'data', y = 'linear', width = 500, height = 400, range_y = [-3, 3])

In [0]:
from tensorflow.keras.activations import sigmoid

data = pd.DataFrame({'data' : random_data, 'sigmoid' : sigmoid(random_data)})
data.head()

data   sigmoid
0 -3.000000  0.047426
1 -2.979933  0.048341
2 -2.959866  0.049272
3 -2.939799  0.050221
4 -2.919732  0.051187

In [0]:
px.line(data, x = 'data', y = 'sigmoid', width = 500, height = 400, range_y = [0, 1])

In [5]:
from tensorflow.keras.activations import relu
data = pd.DataFrame({'data' : random_data, 'relu' : relu(random_data)})
data.head()

data  relu
0 -3.000000   0.0
1 -2.979933   0.0
2 -2.959866   0.0
3 -2.939799   0.0
4 -2.919732   0.0

In [0]:
px.line(data, x = 'data', y = 'relu', width = 500, height = 400, range_y = [0, 1])

In [6]:
from tensorflow.keras.activations import tanh
data = pd.DataFrame({'data' : random_data, 'tanh' : tanh(random_data)})
data.head()

data      tanh
0 -3.000000 -0.995055
1 -2.979933 -0.994853
2 -2.959866 -0.994643
3 -2.939799 -0.994424
4 -2.919732 -0.994196

In [0]:
px.line(data, x = 'data', y = 'tanh', width = 500, height = 400, range_y = [-1, 1])

In [0]:
model = Sequential()
model.add(Dense(units=8, activation='relu', input_shape=(10,)))
model.add(Dense(units=1, activation='sigmoid'))
model.summary()

Model: "sequential_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_12 (Dense)             (None, 8)                 88        
_________________________________________________________________
dense_13 (Dense)             (None, 1)                 9         
Total params: 97
Trainable params: 97
Non-trainable params: 0
_________________________________________________________________


In [0]:
# kompilacja modelu
#(optimizer - optymalizator)
#(loss - funkcja straty)

# klasyfikacja binarna
model.compile(optimizer = 'rmsprop',
              loss = 'binary_crossentropy',
              metrics = ['accuracy'])
# klasyfikacja wieloklasowa
model.compile(optimizer = 'rmsprop',
              loss = 'categorical_cossentropy',
              metrics = ['accuracy'])
# regresja
model.compile(optimizer = 'rmsprop',
              metrics = ['accuracy'])

In [0]:
#Za dane wejściowe do modelu należy przekazać Numpy arrays:

#epochs - krotność przejścia danych przez sieć w procesie uczenia
#batch_size - rozmiar wsadu po którym następuje aktualizacja wag
#validation_split - część danych treningowych, które zostaną wykorzystane jako zbiór walidacyjny
#validation_data - (x_val, y_val) - dane wykorzystane do walidacji modelu

# model.fit(data, labels, epochs=10, batch_size=32)
# model.fit(data, labels, epochs=10, batch_size=32, validation_split=0.2)
# model.fit(data, labels, epochs=10, batch_size=32, validation_data=(x_val, y_val))

In [0]:
data = np.random.randn(10000, 150)
labels = np.random.randint(2, size = (10000, 1))

print(data.shape)
print(labels.shape)

(10000, 150)
(10000, 1)


In [0]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20)

Epoch 1/20
313/313 [==============================] - 0s 1ms/step - loss: 0.7359 - accuracy: 0.5071
Epoch 2/20
313/313 [==============================] - 1s 2ms/step - loss: 0.6924 - accuracy: 0.5444
Epoch 3/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6763 - accuracy: 0.5705
Epoch 4/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6632 - accuracy: 0.5967
Epoch 5/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6503 - accuracy: 0.6192
Epoch 6/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6368 - accuracy: 0.6409
Epoch 7/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6221 - accuracy: 0.6603
Epoch 8/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6070 - accuracy: 0.6777
Epoch 9/20
313/313 [==============================] - 0s 1ms/step - loss: 0.5926 - accuracy: 0.6915
Epoch 10/20
313/313 [==============================] - 0s 1ms/step - loss: 0.5787 - accuracy: 0.7041

In [0]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])
# aktualizacja wag co 32 próbki
model.fit(data, labels, epochs=20, batch_size= 32)

Epoch 1/20
313/313 [==============================] - 0s 1ms/step - loss: 0.7514 - accuracy: 0.5069
Epoch 2/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6925 - accuracy: 0.5509
Epoch 3/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6748 - accuracy: 0.5756
Epoch 4/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6602 - accuracy: 0.6061
Epoch 5/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6457 - accuracy: 0.6294
Epoch 6/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6322 - accuracy: 0.6517
Epoch 7/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6167 - accuracy: 0.6722
Epoch 8/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6017 - accuracy: 0.6815
Epoch 9/20
313/313 [==============================] - 0s 1ms/step - loss: 0.5882 - accuracy: 0.6996
Epoch 10/20
313/313 [==============================] - 0s 1ms/step - loss: 0.5740 - accuracy: 0.7107

In [0]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])
# aktualizacja wag co 32 próbki + dodanie validation split
model.fit(data, labels, epochs=40, batch_size= 32, validation_split = 0.2)

Epoch 1/40
250/250 [==============================] - 0s 2ms/step - loss: 0.7466 - accuracy: 0.5019 - val_loss: 0.7290 - val_accuracy: 0.4955
Epoch 2/40
250/250 [==============================] - 0s 2ms/step - loss: 0.6908 - accuracy: 0.5531 - val_loss: 0.7206 - val_accuracy: 0.4995
Epoch 3/40
250/250 [==============================] - 0s 2ms/step - loss: 0.6715 - accuracy: 0.5824 - val_loss: 0.7197 - val_accuracy: 0.5075
Epoch 4/40
250/250 [==============================] - 0s 1ms/step - loss: 0.6567 - accuracy: 0.6110 - val_loss: 0.7217 - val_accuracy: 0.5005
Epoch 5/40
250/250 [==============================] - 0s 1ms/step - loss: 0.6426 - accuracy: 0.6326 - val_loss: 0.7254 - val_accuracy: 0.5090
Epoch 6/40
250/250 [==============================] - 0s 1ms/step - loss: 0.6277 - accuracy: 0.6610 - val_loss: 0.7353 - val_accuracy: 0.4985
Epoch 7/40
250/250 [==============================] - 0s 1ms/step - loss: 0.6124 - accuracy: 0.6760 - val_loss: 0.7395 - val_accuracy: 0.4980
Epoch 

In [0]:
test_data = np.random.randn(5, 150)

In [0]:
# dostajemy prawdopodobenstwo 
# granica decyzyjna wynosi 1/2
model.predict(test_data)

array([[0.20691639],
       [0.86227536],
       [0.8652682 ],
       [0.8833834 ],
       [0.99309665]], dtype=float32)

In [0]:
model.predict_proba(test_data)

array([[0.20691639],
       [0.86227536],
       [0.8652682 ],
       [0.8833834 ],
       [0.99309665]], dtype=float32)

In [0]:
#zwraca konkretne klasy
model.predict_classes(test_data)

array([[0],
       [1],
       [1],
       [1],
       [1]], dtype=int32)

# Klasyfikacja wieloklasowa

In [22]:
data = np.random.random((10000, 150))
labels = np.random.randint(10, size = (10000, 1))

print(data.shape)
print(data)
print(labels.shape)
print(labels)


(10000, 150)
[[0.84271016 0.88226184 0.05533741 ... 0.36603714 0.80084948 0.43490507]
 [0.45488322 0.65176358 0.92468305 ... 0.75759845 0.07733492 0.72699989]
 [0.75527664 0.05310586 0.36494497 ... 0.085256   0.14515133 0.69150464]
 ...
 [0.13605409 0.77990601 0.40235168 ... 0.47521663 0.72312589 0.48645356]
 [0.1746913  0.50141889 0.72638405 ... 0.97391213 0.13351897 0.84980338]
 [0.12972446 0.32358899 0.91944642 ... 0.7542757  0.34161587 0.28308926]]
(10000, 1)
[[4]
 [2]
 [2]
 ...
 [5]
 [4]
 [1]]


In [23]:
labels[:10]

array([[4],
       [2],
       [2],
       [3],
       [7],
       [4],
       [5],
       [5],
       [3],
       [0]])

In [24]:
from tensorflow.keras.utils import to_categorical
labels = to_categorical(labels, num_classes = 10)
labels

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]], dtype=float32)

In [26]:
labels[0]

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.], dtype=float32)

In [27]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=10, activation='softmax'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, batch_size= 32, epochs = 30, validation_split = 0.2)

Epoch 1/30
250/250 [==============================] - 1s 2ms/step - loss: 0.3266 - accuracy: 0.1023 - val_loss: 0.3259 - val_accuracy: 0.0855
Epoch 2/30
250/250 [==============================] - 0s 2ms/step - loss: 0.3251 - accuracy: 0.1103 - val_loss: 0.3253 - val_accuracy: 0.1015
Epoch 3/30
250/250 [==============================] - 0s 2ms/step - loss: 0.3249 - accuracy: 0.1086 - val_loss: 0.3257 - val_accuracy: 0.0995
Epoch 4/30
250/250 [==============================] - 0s 2ms/step - loss: 0.3246 - accuracy: 0.1166 - val_loss: 0.3263 - val_accuracy: 0.0930
Epoch 5/30
250/250 [==============================] - 0s 1ms/step - loss: 0.3243 - accuracy: 0.1230 - val_loss: 0.3258 - val_accuracy: 0.0965
Epoch 6/30
250/250 [==============================] - 0s 2ms/step - loss: 0.3239 - accuracy: 0.1185 - val_loss: 0.3259 - val_accuracy: 0.1040
Epoch 7/30
250/250 [==============================] - 0s 2ms/step - loss: 0.3235 - accuracy: 0.1271 - val_loss: 0.3268 - val_accuracy: 0.0890
Epoch 

In [28]:
test_data = np.random.random((10, 150))

model.predict(test_data)

array([[0.10032617, 0.0710101 , 0.06711504, 0.08988877, 0.1146206 ,
        0.09235349, 0.17767787, 0.12614784, 0.08245705, 0.07840306],
       [0.10353588, 0.12470841, 0.07571369, 0.11854485, 0.08431756,
        0.08133401, 0.08378258, 0.10883137, 0.11552954, 0.10370212],
       [0.09233666, 0.09668843, 0.07507232, 0.10135043, 0.10450897,
        0.09529485, 0.12514015, 0.11465108, 0.10426372, 0.09069346],
       [0.11310623, 0.10438425, 0.06080963, 0.09444425, 0.07180206,
        0.09877001, 0.06802119, 0.11703497, 0.17651491, 0.09511242],
       [0.0753534 , 0.1231141 , 0.0914491 , 0.03758074, 0.25185096,
        0.08666675, 0.06353766, 0.10638406, 0.09905276, 0.06501049],
       [0.08706655, 0.17915967, 0.17252046, 0.06513783, 0.04798031,
        0.07340922, 0.04614609, 0.20232941, 0.09352158, 0.03272896],
       [0.09729838, 0.08709488, 0.05189393, 0.10202669, 0.11240448,
        0.08692669, 0.10071239, 0.10556778, 0.1008635 , 0.15521131],
       [0.11822914, 0.08135292, 0.0595284

Przykład regresja

In [0]:
data = np.random.random((10000, 150))
labels = 50 * np.random.random(10000)

In [31]:
labels[:10]

array([37.51805934,  0.15397313, 11.10498883, 15.1022522 , 12.35852152,
       35.69397258, 20.67764502, 23.78917341, 49.43940046, 17.65230193])

In [34]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1))

model.compile(optimizer='rmsprop',
              loss='mse',)

model.fit(data, labels, epochs = 32,batch_size = 32, validation_split = 0.2)

Epoch 1/32
250/250 [==============================] - 1s 2ms/step - loss: 249.9042 - val_loss: 212.8871
Epoch 2/32
250/250 [==============================] - 0s 2ms/step - loss: 211.0742 - val_loss: 213.1134
Epoch 3/32
250/250 [==============================] - 0s 2ms/step - loss: 210.5305 - val_loss: 213.4179
Epoch 4/32
250/250 [==============================] - 0s 2ms/step - loss: 209.9669 - val_loss: 213.8687
Epoch 5/32
250/250 [==============================] - 0s 2ms/step - loss: 209.5673 - val_loss: 216.5549
Epoch 6/32
250/250 [==============================] - 0s 2ms/step - loss: 209.1493 - val_loss: 214.4324
Epoch 7/32
250/250 [==============================] - 0s 2ms/step - loss: 208.7437 - val_loss: 216.4763
Epoch 8/32
250/250 [==============================] - 0s 2ms/step - loss: 208.7717 - val_loss: 214.7785
Epoch 9/32
250/250 [==============================] - 0s 2ms/step - loss: 208.4958 - val_loss: 215.4814
Epoch 10/32
250/250 [==============================] - 0s 2ms/st

In [35]:
test_data = np.random.random((10,150))

model.predict(test_data)

array([[26.769884],
       [21.256178],
       [20.266562],
       [22.31701 ],
       [22.343382],
       [25.913095],
       [27.197744],
       [21.77517 ],
       [26.703173],
       [27.302324]], dtype=float32)